// AUTO-GENERATED from lib/Districts_Regions_Products.csv. Do not edit by hand.
// The CSV holds three INDEPENDENT alphabetical lists (District, Region, Product)
// stacked side by side; they are not related row by row.

export const districts = [
  "ADILABAD",
  "AGAR",
  "AGAR MALWA",
  "AGRA",
  "AHILYANAGAR",
  "AHMED NAGAR",
  "AHMEDNAGAR DISTRICT",
  "AJMER",
  "AKOLA",
  "AKOLA DISTRICT",
  "ALIGARH",
  "ALIRAJPUR",
  "ALLURI SITHARAMA RAJU DISTRICT",
  "ALWAR",
  "AMBALA",
  "AMBEDKAR NAGAR",
  "AMETHI",
  "AMRAVATI",
  "AMRITSAR",
  "AMROHA",
  "ANAND",
  "ANANTAPUR",
  "ANANTAPURAM",
  "ANNAMAYYA",
  "ANUPGARH",
  "ARARIA DISTRICT",
  "ARAVALLI",
  "ARVALLI",
  "ASHOKNAGAR",
  "AURAIYA",
  "AURANGABAD",
  "AYODHYA",
  "AZAMGARH",
  "BADAUN",
  "BADER",
  "BAGALKOTE",
  "BAHADURGARH",
  "BAHRAICH",
  "BALAGHAT",
  "BALETA",
  "BALLARI",
  "BALLIA",
  "BALOD",
  "BALRAMPUR",
  "BANASKANTHA",
  "BANKA",
  "BANKURA",
  "BANSWARA",
  "BARA",
  "BARABANKI",
  "BARAN",
  "BAREILLY",
  "BARMER",
  "BARPETA",
  "BARWANI",
  "BASTAR",
  "BASTI",
  "BATHINDA",
  "BEAWAR",
  "BEAWARE",
  "BEED DISTRICT",
  "BEGUSARAI",
  "BEHROR",
  "BELAGAVI",
  "BELKHADU",
  "BELLARY",
  "BEMETARA",
  "BEMETRA",
  "BENGALURU",
  "BENGALURU URBAN",
  "BETUL",
  "BHADOHI",
  "BHADRADRI KOTHAGUDEM",
  "BHADRADRIKOTHAGUDEM",
  "BHAGALPUR",
  "BHARATPUR",
  "BHARUCH",
  "BHATINDA",
  "BHAVNAGAR",
  "BHILWARA",
  "BHIND",
  "BHIWANI",
  "BHOJPUR",
  "BHOPAL",
  "BHUPALPALLY",
  "BIJNOR",
  "BIJWAD NARUKA",
  "BIKANER",
  "BILASPUR",
  "BISAULI",
  "BONGAIGAON",
  "BULANDSHAHR",
  "BULDHANA DISTRICT",
  "BUNDI",
  "BURHANPUR",
  "BUXAR",
  "CHAMARAJANAGAR",
  "CHAMARAJANAGARA",
  "CHAMPA",
  "CHANDAULI",
  "CHAPPER",
  "CHAPRA",
  "CHATRA",
  "CHHATARPUR",
  "CHHATRAPATI SAMBHAJINAGAR DISTRICT",
  "CHHINDWARA",
  "CHHOTA UDAIPUR",
  "CHHOTAUDAIPUR",
  "CHIKKABALLAPURA",
  "CHINTAMANI",
  "CHIRANG",
  "CHITRADURGA",
  "CHITTORGARH",
  "CHOMU",
  "CHURU",
  "COOCH BEHAR",
  "DAKSHIN DINAJPUR",
  "DAMOH",
  "DARBHANGA",
  "DARRANG",
  "DATIA",
  "DAUSA",
  "DEEG",
  "DEOGHAR",
  "DEORIA",
  "DEVBHUMI DWARKA",
  "DEWAS",
  "DHAMTARI",
  "DHANPURI",
  "DHANUSHA",
  "DHAR",
  "DHAULPUR",
  "DHOLPUR",
  "DIDWANA KUCHAMAN",
  "DINAJPUR",
  "DUMRI",
  "DURG",
  "EAST CHAMPARAN",
  "ETAH",
  "ETAWAH",
  "FARIDABAD",
  "FARIDKOT",
  "FARRUKHABAD",
  "FATEHABAD",
  "FATEHGARH SAHIB",
  "FATEHPUR",
  "FAZILKA",
  "FEROZEPUR",
  "FIROZABAD",
  "FIROZPUR",
  "GANDHINAGAR",
  "GAYA",
  "GHANAUR",
  "GHAZIPUR",
  "GIRIDIH",
  "GOALPARA",
  "GOLAGHAT",
  "GONDA",
  "GONDIYA",
  "GOPALGANJ",
  "GORAKHPUR",
  "GUNA",
  "GUNTUR",
  "GURDASPUR",
  "GURGAON",
  "GWALIOR",
  "HAMIRPUR",
  "HANUMANGARH",
  "HAPUR",
  "HARDA",
  "HARDOI",
  "HARIDWAR",
  "HATHRAS",
  "HAZARIBAGH",
  "HINGOLI",
  "HISAR",
  "HOJAI",
  "HOOGHLY",
  "HOSAKOTA",
  "HOSHANGABAD",
  "HOSHIARPUR",
  "INDORE",
  "JABALPUR",
  "JABERA",
  "JAGITIA",
  "JAIPUR",
  "JAIPUR(RURAL)",
  "JAISALMER",
  "JALANDHAR",
  "JALAUN",
  "JALGAON",
  "JALGAON DISTRICT",
  "JALNA",
  "JALNA DISTRICT",
  "JALORE",
  "JALPAIGURI",
  "JALPAIGURI DISTRICT",
  "JAMNAGAR",
  "JAMUI",
  "JANJGIR-CHAMPA",
  "JAUNPUR",
  "JAYASHANKAR BHUPALAPALLY",
  "JHABUA",
  "JHAJJAR",
  "JHALAWAR",
  "JHANSI",
  "JHUNJHUNU",
  "JODHPUR",
  "JODHPUR(RURAL)",
  "JORHAT",
  "JUNAGADH",
  "KABIRDHAM",
  "KACHCHH",
  "KADAPA DISTRICT",
  "KAIMUR",
  "KAITHAL",
  "KALABURAGI",
  "KANGRA",
  "KANNAUJ",
  "KANPUR",
  "KANPUR DEHAT",
  "KANPUR NAGAR",
  "KANPURDEHAT",
  "KAPURTHALA",
  "KARAULI",
  "KARIMNAGAR",
  "KARNAL",
  "KASGANJ",
  "KATIHAR",
  "KATNI",
  "KAUSHAMBI",
  "KHAGARIA",
  "KHAMMAM",
  "KHANDWA",
  "KHARGONE",
  "KHEDA",
  "KHERTHAL-TIJARA",
  "KOLAR",
  "KOMURAMBHEAM ASIFABAD",
  "KONDAGAON",
  "KOPPAL",
  "KORIYA",
  "KOTA",
  "KOTHPUTLI",
  "KOTPUTLI-BEHROR",
  "KRISHNA DISTRICT",
  "KUMURAM BHEEM ASIFABAD",
  "KURNOOL",
  "KURUKSHETRA",
  "KUSHINAGAR",
  "LAKHIMPUR",
  "LAKHIMPUR KHERI",
  "LAKHISARAI",
  "LALITPUR",
  "LATEHAR",
  "LUCKNOW",
  "LUDHIANA",
  "MADHEPURA",
  "MADHUBANI",
  "MAHASAMUND",
  "MAHENDARGARH",
  "MAHENDRAGARH",
  "MAHESANA",
  "MAHOBA",
  "MAHOTTARI",
  "MAHRAJGANJ",
  "MAINPURI",
  "MALAKHERA",
  "MALDA",
  "MALDAH",
  "MANDI",
  "MANDSAUR",
  "MANDYA",
  "MANENDRAGARH-CHIRIMIRI-BHARATPUR",
  "MANSA",
  "MARIGAON",
  "MATHURA",
  "MAUGANJ",
  "MAZWARI",
  "MEERUT",
  "MIRZAPUR",
  "MOGA",
  "MORABI",
  "MORADABAD",
  "MORENA",
  "MUKTSAR",
  "MULUGU",
  "MUNGELI",
  "MUNGER",
  "MURSHIDABAD",
  "MUZAFFARNAGAR",
  "MUZAFFARPUR",
  "MYSORE",
  "NADIA",
  "NAGAON",
  "NAGAUR",
  "NAGPUR",
  "NALANDA",
  "NALGONDA",
  "NANDED",
  "NANDED DISTRICT",
  "NANDYAL",
  "NARMADA",
  "NARMADAPURAM",
  "NARSINGHPUR",
  "NASHIK",
  "NASHIK DISTRICT",
  "NAWADA",
  "NAWANAGAR",
  "NEEM KA THANA",
  "NEEMUCH",
  "NELLORE",
  "NIPHAD",
  "NIWARI",
  "NIZAMABAD",
  "NORTH 24 PARGANAS",
  "NORTH 24-PARGANAS",
  "NTR",
  "NUH",
  "NUNSAR",
  "PALAMAU",
  "PALNADU",
  "PALWAL",
  "PANDHURNA",
  "PANIPAT",
  "PANNA",
  "PARSA",
  "PATAN",
  "PATHANKOT",
  "PATHRIYA",
  "PATIALA",
  "PATNA",
  "PEDDAPALLI",
  "PETLAWAD",
  "PHALODI",
  "PRAKASAM",
  "PRATAPGARH",
  "PRAYAGRAJ",
  "PUNE",
  "PUNE DISTRICT",
  "PURNEA",
  "PURNIA",
  "RAEBARELI",
  "RAEBARELY",
  "RAICHUR",
  "RAIPUR",
  "RAISEN",
  "RAJGARH",
  "RAJKOT",
  "RAJNANDGAON",
  "RAMPUR",
  "RANCHI",
  "RANGA REDDY",
  "RATLAM",
  "RAUTAHAT",
  "REWA",
  "REWARI",
  "ROHTAK",
  "ROHTAS",
  "ROPAR",
  "RUPNAGAR",
  "SABARKANTHA",
  "SAGAR",
  "SAHARANPUR",
  "SAHARSA",
  "SAHEBGANJ",
  "SAHIBGANJ",
  "SAHIBZADA AJIT SINGH NAGAR",
  "SAMASTIPUR",
  "SAMBHAJINAGAR",
  "SAMBHAL",
  "SANAUR",
  "SANGAREDDY",
  "SANGLI",
  "SANGLI DISTRICT",
  "SANGRUR",
  "SANT KABIR NAGAR",
  "SANT RAVIDAS NAGAR",
  "SARAN",
  "SARANGARH-BILAIGARH",
  "SARLAHI",
  "SATARA",
  "SATNA",
  "SAWAI MADHOPUR",
  "SEHORE",
  "SEONI",
  "SHAHDOL",
  "SHAHEED BHAGAT SINGH NAGAR",
  "SHAHJAHANPUR",
  "SHAHPURA",
  "SHAJAPUR",
  "SHAMLI",
  "SHEOPUR",
  "SHIMLA",
  "SHIVPURI",
  "SHRAVASTI",
  "SHYAM GANGA",
  "SIDDHARTHNAGAR",
  "SIDDIPET",
  "SIDHI",
  "SIKAR",
  "SINGRAULI",
  "SIRAHA",
  "SIRMAUR",
  "SIROHI",
  "SIRSA",
  "SITAMARHI",
  "SITAPUR",
  "SIWAN",
  "SOLAN",
  "SOLAPUR",
  "SOLAPUR DISTRICT",
  "SONBHADRA",
  "SONIPAT",
  "SONITPUR",
  "SOUTH 24 PARGANAS",
  "SOUTH 24-PGNS",
  "SPSR NELLORE DISTRICT",
  "SRI GANGANAGAR",
  "SRI MUKTSAR SAHIB",
  "SRI POTTI SRIRAMULU NELLORE",
  "SRI SATHYA SAI",
  "SRIGANGANAGAR",
  "SULTANPUR",
  "SUPAUL",
  "SURAJPUR",
  "SURENDRANAGAR",
  "SURGUJA",
  "SURYAPET",
  "TARAN TARN",
  "TARN TARAN",
  "THANDLA",
  "TIJARA",
  "TIKAMGARH",
  "TIRUPATI",
  "TONK",
  "TULSIPUR",
  "UDAIPUR",
  "UDALGURI",
  "UJJAIN",
  "UMARIA",
  "UNA",
  "UNNAO",
  "UTTAR DINAJPUR",
  "VADODARA",
  "VAISHALI",
  "VARANASI",
  "VAV-THARAD",
  "VIDISHA",
  "VIJAYANAGR",
  "VIJAYAPURA",
  "WARANGAL",
  "WARDHA",
  "WASHIM",
  "WEST CHAMPARAN",
  "WEST KARBI ANGLONG",
  "YADGIR",
  "YADGIRI",
  "YAMUNANAGAR",
  "YAVATMAL",
  "YAVATMAL DISTRICT"
];

export const products = [
  "1201",
  "131",
  "1616",
  "1666",
  "2,4 D Amine Salt 58%",
  "2,4 D Sodium Salt 80",
  "2,4,D Ethyl ester 38%",
  "2110",
  "2112",
  "2205",
  "2209",
  "2217",
  "23",
  "234",
  "2372",
  "331",
  "361",
  "371",
  "412",
  "422",
  "432",
  "433",
  "453",
  "456",
  "470",
  "5001",
  "5501",
  "5505",
  "5511",
  "5580",
  "567 (Safeda)",
  "611",
  "65",
  "71",
  "732",
  "734",
  "734 Gold",
  "735",
  "754 Gold",
  "7891",
  "822",
  "8860",
  "8866",
  "8870",
  "89",
  "9220",
  "9660",
  "9662",
  "9698",
  "9700",
  "9701",
  "9705",
  "9718",
  "9865",
  "Abha",
  "Acriter",
  "Acrius",
  "Akina",
  "Albela",
  "Aleksy",
  "Ankita",
  "Annika",
  "Atrazine",
  "B-70",
  "BIKUTA",
  "Babli",
  "Benzo",
  "Bio 605",
  "Borky",
  "Bucona",
  "CHRONE",
  "CROP PROTECTION - TREXTER",
  "Calico",
  "Calific",
  "Carbo",
  "Cartap 4G",
  "Cartap 50 SP",
  "Carzeb",
  "Charu Super",
  "Chlor Plus",
  "Chloro",
  "Ciptrole GR",
  "Ciptrole SC",
  "DEVIKA",
  "DOPPELT",
  "Dart",
  "Dart Plus",
  "Dhaal",
  "Dhoom",
  "DripIT Grapes",
  "DripIT Pome",
  "DripIT Vegetables",
  "Early",
  "Festura",
  "Fipgra",
  "Fiprid",
  "Fipro SC",
  "Fipronil",
  "Floxy",
  "Forza",
  "Ganga",
  "Gazab",
  "Godavari",
  "Gold",
  "Gomti",
  "Gori",
  "Green Bank",
  "HARSHA",
  "Heena",
  "Hopnip",
  "ISO",
  "Jaivodaya",
  "Jhilmil",
  "Joso",
  "Kamya Gold",
  "Kanchi",
  "Khushboo",
  "Kibush",
  "Lali",
  "Latika",
  "MAHARAJA",
  "MSM",
  "Magnica",
  "Mahak",
  "Mancozeb",
  "Mariko",
  "Metasy",
  "Metri",
  "Mono",
  "Multi soft",
  "Myro-NXT",
  "NAZMI",
  "Nano",
  "No  94",
  "NuCrop",
  "PRABHAT",
  "Paddy 303",
  "PaddyStar",
  "Paraquat",
  "Pend-Ultra",
  "Picasol",
  "Pinocio",
  "Pooja",
  "Pretila",
  "Pretilachlor 37",
  "Profen",
  "Profen Plus",
  "Protobuz",
  "Protobuz+",
  "RAGINI",
  "Rajkumar Gold",
  "Razor",
  "Reprozin",
  "SAISHO",
  "SALONI",
  "SANSANI",
  "SHOBHA",
  "SOFTGOLD",
  "SR-35",
  "SUGANDHI",
  "SULEKHA",
  "SUPER 3-SR-72",
  "SUPER 7711",
  "SWETA",
  "Samridhi",
  "Sateer",
  "Selection 200",
  "Shaasak",
  "Sheetal",
  "Shera",
  "Shipra",
  "Shriam Sulphur 80% WDG",
  "SprayIT Cereals",
  "SprayIT Cotton",
  "SprayIT Potato",
  "SprayIT Sugarcane",
  "SprayIT Vegetables",
  "Sundari",
  "Super 1-SR-14",
  "Super 1-SR-15",
  "Super 111",
  "Super 21-SR-31",
  "Super 23-SR-31",
  "Super 252",
  "Super 272",
  "Super 303",
  "Super 404",
  "Super 4400",
  "Super 4411",
  "Super 4433",
  "Super 4466",
  "Super 5-SR-05",
  "Super 505",
  "Super 7700",
  "Super 7733",
  "Super Nano",
  "Super Selection SLG 200",
  "Supravet",
  "TREXTER",
  "Tanika",
  "Ultrazib",
  "Urea",
  "Verlust",
  "WEEDOMA",
  "ZARWIN",
  "Zindrip",
  "Ziva-NXT",
  "Ziva-WP"
];

export const regions = [
  "Abohar",
  "Agar",
  "Agra",
  "Ahilyanagar",
  "Ajmer",
  "Akola",
  "Aligarh",
  "Alwar",
  "Ambikapur",
  "Amritsar",
  "Anantapur",
  "Ayodhya",
  "Azamgarh",
  "Bahraich",
  "Balaghat",
  "Ballia",
  "Banswara",
  "Baran",
  "Barasat",
  "Bareilly",
  "Barmer",
  "Barpeta",
  "Barwani",
  "Begusarai",
  "Belagavi",
  "Bellary",
  "Bhagalpur",
  "Bharatpur",
  "Bhatinda",
  "Bhavnagar",
  "Bhilwara",
  "Bhinmal",
  "Bhopal",
  "Bilaspur",
  "Burdwan",
  "Chapra",
  "Chhindwara",
  "Chikkaballapur",
  "Chittorgarh",
  "Dausa",
  "Dewas",
  "Dhamtari",
  "Dhar",
  "Dholpur",
  "Durg",
  "Etawah",
  "Ferozepur",
  "Gaya",
  "Gorakhpur",
  "Guntur",
  "Gurdaspur",
  "Gwalior",
  "Hanumangarh",
  "Hardoi",
  "Hathras",
  "Hazaribagh",
  "Himatnagar",
  "Hindaun",
  "Hisar",
  "Hisar Rbm",
  "Hoshangabad",
  "Indore",
  "Jabalpur",
  "Jaipur",
  "Jalandhar",
  "Jalgaon",
  "Jhalawar",
  "Jhansi",
  "Jhunjhunu",
  "Jind",
  "Jodhpur",
  "Junagadh",
  "Kanpur",
  "Karimnagar",
  "Karnal",
  "Katni",
  "Khairthal",
  "Khammam",
  "Khandwa",
  "Khargone",
  "Kondagaon",
  "Kota",
  "Kothputli",
  "Kurnool",
  "Kurukshetra",
  "Lucknow",
  "Ludhiana",
  "Madanapalli",
  "Madhepura",
  "Mahesana",
  "Mainpuri",
  "Malda",
  "Mandi",
  "Meerut",
  "Miryalaguda",
  "Miryalguda",
  "Moradabad",
  "Motihari",
  "Muzaffarnagar",
  "Muzaffarpur",
  "Mysore",
  "Nadiad",
  "Nagaon",
  "Nagpur",
  "Nanded",
  "Nashik",
  "Nepal",
  "Nizamabad",
  "Ongole",
  "Palwal",
  "Patiala",
  "Patna",
  "Pratapgarh",
  "Prayagraj",
  "Pune",
  "Purnea",
  "Rajkot",
  "Ranchi",
  "Ratlam",
  "Rewa",
  "Rewari",
  "Sagar",
  "Saharanpur",
  "Sambhajinagar",
  "Sangli",
  "Sangrur",
  "Saraipali",
  "Sawaimadhopur",
  "Sehore",
  "Shahjahanpur",
  "Shimla",
  "Shivpuri",
  "Sidharth Nagar",
  "Sikar",
  "Siliguri",
  "Sirsa",
  "Solan",
  "Solapur",
  "Sonipat",
  "Sriganganagar",
  "Surendranagar",
  "Telangana",
  "Vadodara",
  "Varanasi",
  "Vijayapura",
  "Vijayawada",
  "Yavatmal"
];
